ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false

    # IMU configuration
    imu0: /imu/data
    imu0_config: [false, false, false,  # Position
                  true,  true,  true,   # Orientation
                  false, false, false,  # Linear velocity
                  false, false, true,   # Angular velocity
                  false, false, false]  # Acceleration
    imu0_differential: false
    imu0_relative: true
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    # GPS configuration
    gps0: /fix
    gps0_config: [true, true, false,   # Use position x, y (latitude, longitude)
                  false, false, false, # No velocity data
                  false, false, false] # No other data
    gps0_queue_size: 10
    gps0_relative: false

    # Frame settings
    map_frame: map
    odom_frame: odom
    base_link_frame: imu_link
    world_frame: odom
    publish_tf: true

